### ISSUE TITLE
关于Train Set [Images&Text]:

### ISSUE THREAD

**Issue by yujiasunwp** [AWCXV/TextFusion#2]
请问为什么train set给的下载链接中的数据集只有2000对图像-文本数据集，不是文章中提到的10000呢~

**Comment by AWCXV** [comment]
你好，我们是给2000对图像每个图像对分别标注了5条文本，一共10, 000对红外-可见光-文本三元组。这和论文的实验设置描述是一致的。在最后的版本里，我们会说得更明确一些。
