### ISSUE TITLE
LLVIP测试集目标检测Label

### ISSUE THREAD

**Issue by songwenhao123** [AWCXV/TextFusion#3]
您好，您是否可以分享一下LLVIP测试集目标检测Label？十分感谢！

**Comment by AWCXV** [comment]
你好，现在你可以在Test Set的谷歌云盘里找到它了。[链接](https://drive.google.com/drive/folders/1a5fAg5wDYW0ZrIpaFPVR948zdmuAe2jQ?usp=sharing)

**Comment by WenhaoSong-1512** [comment]
好的，感谢您的帮助。
